# proxy:
#   image: marvambass/nginx-ssl-secure
#   ports: 
#     - "80:80"
#     - "443:443"
#   volumes:
#     - "./proxy:/etc/nginx/external/"
#   links:
#     - web
web:
  build: .
  dockerfile: Dockerfile
  environment:
    - NODE_ENV=development
    - PORT=3000
  volumes:
    - .:/src
  ports:
    - "3000:3000"
  links:
    - mongo

mongo:
   image: mongo
   ports:
     - "27017:27017"